### PR TITLE
Workaround for line comments

### LINKED ISSUE #29: //-style comments are mangled by the plugin
When using line comments, they get their newline stripped by the minification and they become an erroneous selector.

<strike>I was also not able to turn off minify with the plugin options.</strike> (config error)

I propose that minification be disabled until #26 lands, that will be much more useful and correct.

### PR DESCRIPTION
**Pull request by vdanchenkov**
fixes #29

### CODE REVIEW

**Comment by kopax** [comment]
While waiting for this, is it normal that I still see CSS comments in my compressed project using this plugins ?

**Comment by wmertens** [comment]
🎉 , but just curious why you don't just let stylis handle the minifying? Stylis supports line comments… (I'm probably missing something basic)

**Comment by mxstbr** [comment]
> why you don't just let stylis handle the minifying?

Then you're shipping un-minified styles in your JS bundle which are massively huge, we have to do that at build time.

**Comment by wmertens** [comment]
how about processing with stylis at build time as well? Replace the interpolations with known constants that you then split back on?

**Comment by mxstbr** [comment]
That's what @philpl is working on in the open PR, but it might not be ready in time so this is a good intermediary solution.

**Pull request merged**
