### PR TITLE
Clarify message about plugin being needed for SSR

### PR DESCRIPTION
**Pull request by p-jackson**
Updated the docs after the discussion in #39.

Removed the overall bold styling so more specific bold styling could be done. I think the emoji's make it stand out enough any, unlikely it'll be missed.

### CODE REVIEW

**Comment by evan-scott-zocdoc** [comment]
I have one additional question to ask in regards to the SSR feature that may be useful as a readme comment as well:

Does `ssr: true` need to be added to the client-side bundle config as well, or only the server-side bundle config? @philpl

So for instance, webpack bundle #1 has target: node for SSR and bundle #2 has target: web for browsers.

**Comment by mxstbr** [comment]
It needs to be added to both!

**Comment by mxstbr** [comment]
The documentation has been moved to the [website](https://github.com/styled-components/styled-components-website), mind submitting a PR over there?

**Comment by p-jackson** [comment]
All good. I actually think the first paragraph of the new docs explains the plugin perfectly, so doesn't need this change.

Really like the new website by the way 👍

**Comment by mxstbr** [comment]
Thank you for the kind words!

**Pull request closed without merging**
