### PR TITLE
handle complex expressions inside CSS prop object syntax

### LINKED ISSUE #352: Usage of css prop broken in 1.13.2
Hi,

Upgrading this library from v1.12.0 to v1.13.2 is breaking my app builds. I've pinned it down to a specific component that it's using the `css` prop as follows:
```
const MyComponent = ({ width, ...props }) => {
  return (
    <ThirdPartyComponent css={{ width: width ? `${width}px` : '100%' }} {...props} />;
  );
};
```
For the record, the issue still happens when using an HTML tag (i.e. `div`) instead of a custom `ThirdPartyComponent`.

Is this a bug or is it intended behaviour after the upgrade?

**Note:** I'm building my application with the latest versions of Webpack 5 and Babel 7, and using styled-components@5.2.3

### PR DESCRIPTION
**Pull request by probablyup**
fixes #352

### CODE REVIEW

**Comment by klarstrup** [comment]
One of these changes broke my thing that isn't using the object syntax, I hope to find out more later but just an immediate FYI

**Comment by probablyup** [comment]
@klarstrup must be something to do with this change: https://github.com/styled-components/babel-plugin-styled-components/pull/359/files#diff-ef6a6ffba3d725918f184d76241892f9e7ac878aa3891cce860feea7648794b3L125

If you can come up with an example of the syntax that triggers the error, would appreciate it.

**Comment by klarstrup** [comment]
You'll have to excuse the cobbled together repro but here you see the problem at a glance:

v2.0.1
image

v2.0.0
image

**Comment by klarstrup** [comment]
So in short there's an issue of spread `...props` disappearing when combined with `css` within a render prop (but this also happens if one copies out the render prop function into for example a `useMemo`)

**Comment by klarstrup** [comment]
fix is in btw https://github.com/styled-components/babel-plugin-styled-components/pull/361

**Pull request merged**
