### PR TITLE
Safe check for argument properties

### PR DESCRIPTION
**Pull request by ghoshArnab**
Screenshot 2021-07-05 at 6 10 51 PM

### CODE REVIEW

**Comment by probablyup** [comment]
@ghoshArnab do you happen to have a code sample of where it broke so I can add a regression test?

**Comment by probablyup** [comment]
@ghoshArnab just checked and this isn't available until Node 14, so we can't use this syntax for the time being because the 1.x semver branch doesn't have a node "engines" requirement. Could you switch the code to something more compatible?

**Review by ghoshArnab — COMMENTED** [review]
Removed optional chaining operator

**Comment by probablyup** [comment]
Added these in 0c16c1bac6b2a86bac66cf2527f1b05b896019b8, thanks!

**Pull request closed without merging**
