### PR TITLE
preserve structure of JSX member expressions in generated ast nodes

### LINKED ISSUE #240: CSS prop is breaking build when component comes from imported object
**Problem**

When trying to add `css` to a component that comes from a different file from inside an object, an error gets thrown with the message `Uncaught ReferenceError: Icons is not defined`. Strangely the error only occurs in the production build. In development-mode everything is working fine. Also when I move the content of the `icons.tsx` inside the `app.tsx` everything is working as expected as well.

**Setup**
```
// icons.tsx
import React from "react";

const icons = { Foo: (props: any) => <div {...props}>Foo</div> };

export default icons;
```

```
// app.tsx
import React from "react";
import { css } from "styled-components/macro";
import Icons from "./icons";

const someCss = css` background: purple;`;

const App: React.FC = () => { return <Icons.Foo css={someCss} />; };
```
Repo with an example setup: https://github.com/dlehmhus/styled-components-with-macro-example

### PR DESCRIPTION
**Pull request by sfishel18**
this makes sure that other babel transformations that rename variables will be able to process the ast nodes created by this plugin

fixes #240

### CODE REVIEW

**Comment by vedrani** [comment]
Tested it out on my problem, it works.

**Comment by denieler** [comment]
yep, looks like I'm experiencing the same issue and it looks like this fix works for me 👍

**Comment by denieler** [comment]
@mxstbr @probablyup is it possible to merge this fix?

**Comment by inemiro** [comment]
Truly waiting!

**Comment by teimurjan** [comment]
Looking forward to this fix! 🙏

**Comment by denieler** [comment]
hey guys, any progress on merging this PR?

**Comment by havenchyk** [comment]
@probablyup could you please take a look, I'm waiting for this change

**Comment by dmaklygin** [comment]
Hey, let's merge it!

**Review by kitten — APPROVED** [review]

**Pull request merged**
