### PR TITLE
Add namespace option

### PR DESCRIPTION
**Pull request by rajzik**
This is a fix of [2974](https://github.com/styled-components/styled-components/issues/2974).

I have already implemented fork of this repo and tested it with my adoption: 
[@rajzik/babel-plugin-styled-components](https://github.com/rajzik/babel-plugin-styled-components-namespace).

It is working well and it creates a unique name with the given namespace.
This will resolve all issues with micro frontends class name duplication.

### CODE REVIEW

**Comment by pgangwani** [comment]
Dear core contributors,
Could you please review this PR?
This is only option I see working for me where I have micro-frontend setup composed using ESI at akamai (cdn). Please suggest if there is any other way which we are missing.

@mxstbr  @probablyup @kitten

**Comment by bowsersenior** [comment]
I was looking for exactly this feature to solve a production bug with clashing class names generated by styled-components. It would be awesome to have this feature available!

**Comment by rajzik** [comment]
@bowsersenior as for now, I have released fork with namespace setting 
[plugin-namespace](https://github.com/rajzik/babel-plugin-styled-components-namespace).
It is just fork with namespace added so you can substitute babel-plugin-styled-component with mine.
I am using it, and it works well.

**Comment by luanraithz** [comment]
I'm also having a production bug related to multiple styled-components instances conflicting.

**Comment by dlcognite** [comment]
this would also solve a lot of the issues i am having as well, ping again :P

**Comment by probablyup** [comment]
If someone could add some docs to the website, that'd be awesome: https://github.com/styled-components/styled-components-website/issues/696

**Pull request merged**
