### PR TITLE
reintroduce "pure" tagging

### PR DESCRIPTION
**Pull request by probablyup**
I found and fixed some issues with the original implementation which is why it probably was so slow.

```
npm i --save-dev babel-plugin-styled-components@experimental
```

`.babelrc`

```json
{
  "plugins": [
    ["babel-plugin-styled-components", { "pure": true }]
  ]
}
```

### CODE REVIEW

**Comment by probablyup** [comment]
Can test it with `babel-plugin-styled-components@experimental`

**Comment by probablyup** [comment]
The only thing I'm not sure about is technically `keyframes` is not pure prior to v4, but if you don't interpolate it somewhere then you're not using the animation... so it does it matter?

**Comment by probablyup** [comment]
Yeah it's off by default for now

**Comment by brad-decker** [comment]
Thanks for your work here! <3

**Pull request merged**
