### PR TITLE
Support nested + lowercase components

### PR DESCRIPTION
**Pull request by bpierre**
This is to support the [Animated](https://github.com/animatedjs/animated) library used by [react-spring](https://www.react-spring.io/) with the `css` prop.

Pseudocode to illustrate:

```jsx
// in
<animated.div css="color: red" />
```

```jsx
// out (before the change)
styled("animated.div")`
  color: red
`
```

```jsx
// out (after the change)
styled(animated.div)`
  color: red
`
```

### CODE REVIEW

**Comment by bpierre** [comment]
Is there anything I can do to make this easier to review?

**Comment by probablyup** [comment]
Can we drop the web component support bit? Just not widely-enough used and React [barely supports them](https://reactjs.org/docs/web-components.html) as-is.

**Comment by probablyup** [comment]
I'm going to merge your PR [into mine](https://github.com/styled-components/babel-plugin-styled-components/pull/228) as it has some other css prop changes and the fixtures are going to have further merge conflicts

**Comment by probablyup** [comment]
Cherry-picked over to #228 with authorship retained, thanks!

**Pull request closed without merging**
