### PR TITLE
Pass-through babel-types in visitors to be version agnostic

### PR DESCRIPTION
**Pull request by kitten**
Alternative to https://github.com/styled-components/babel-plugin-styled-components/pull/128

cc @existentialism

### CODE REVIEW

**Comment by kitten** [comment]
@existentialism that sounds good; but I'd feel that would belong in a new-ish Babel 7 PR that upgrades some dependencies (to **non-beta** versions). Then we can add a sanity check that checks the lib against both versions :smile:

Not sure whether option 2 is strictly necessary, as long as both are interchangeable for us

**Comment by iamsolankiamit** [comment]
@mxstbr Can this be merged?

**Comment by kitten** [comment]
@probablyup oh dear, totally forgot to get this merged in time 😅😅😅

**Comment by probablyup** [comment]
@kitten I think this is mergeable now?

**Comment by existentialism** [comment]
LGTM!

**Comment by probablyup** [comment]
Lezzzz do it

**Pull request merged**
