### PR TITLE
Add Babel 7

### PR DESCRIPTION
**Pull request by damassi**
Swaps out Babel 6 with Babel 7, and updates Jest to latest.

### CODE REVIEW

**Comment by probablyup** [comment]
I'd like to wait on this until Babel 7 final is out

**Comment by existentialism** [comment]
Beyond changing the build deps, one other option is to _remove_ the hard dependency on `babel-types`/`@babel-types`, and instead pass the types that are passed directly to the plugin to the util functions, as I mentioned back when we [added pure comments](https://github.com/styled-components/babel-plugin-styled-components/pull/117#discussion_r161072446).

**Comment by kitten** [comment]
@existentialism I never understood why we haven't set that up in the first place. If someone here is up for PRing this that'd be AWESOME :tada:

**Comment by damassi** [comment]
Closing in favor of #134

**Pull request closed without merging**
