### PR TITLE
Use file.opts.filename instead of file.opts.basename for babel 7 compatibility

### PR DESCRIPTION
**Pull request by lixiaoyan**
https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors

### CODE REVIEW

**Comment by lixiaoyan** [comment]
@JamieDixon Seems both filename and basename are available in Babel 6, but in Babel 7 only filename.

**Comment by mxstbr** [comment]
It seems they are different things though? The changelog says 

> The opts.basename option exposed on state.file.opts has been removed. **If you need it, best to build it from opts.filename yourself**

But it doesn't say how to do that 🙃 /cc @loganfsmyth maybe has some wisdom to drop here?

**Comment by lixiaoyan** [comment]
https://github.com/babel/babel/pull/5467/files#diff-d6903991e1c21aaacc4d615157f587e5L144
Seems babel use a different way to get basename but I'm sure they are same.
Anyway, I'll update my code to follow the way babel used.

**Comment by loganfsmyth** [comment]
Good call, thanks for cleaning this up. This option was never documented anywhere and it just didn't seem like something worth having since you can do this to get it from the filename.

**Comment by lixiaoyan** [comment]
Could you make a release for this, thanks.

**Comment by mxstbr** [comment]
Of course, my bad!

**Pull request merged**
