### PR TITLE
Transpile template literals

### PR DESCRIPTION
**Pull request by vdanchenkov**
Another feature for those who care about minification. @mxstbr Please put attention on docs and suggest/make changes if something there is difficult to comprehend.

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks great! Is there any reason to not enable this by default?

**Comment by vdanchenkov** [comment]
@mxstbr This is something I was not sure about. The only reason to disable I can see is that transpilation will make bundle size slightly bigger given you don't care about transpilation at all. 

But you can always disable this feature in that rare case... Actually, I'm thinking about making it enabled by default as it's the case for most users.

**Comment by mxstbr** [comment]
Yeah that sounds reasonable to me!

**Comment by vdanchenkov** [comment]
Made it enabled by default and updated docs.

**Pull request merged**
